CREATE TABLE "ORDERS" (
  "ID" int PRIMARY KEY,
  "CUSTOMER_NAME" varchar NOT NULL,
  "DELIVERY_ADDRESS" varchar NOT NULL,
  "ORDER_TAKER_NAME" varchar,
  "DELIVERY_DATE" timestamp NOT NULL,
  "CREATED_AT" timestamp DEFAULT (now())
);
 
CREATE TABLE "PRODUCTS" (
  "NAME" varchar PRIMARY KEY,
  "UNIT" varchar NOT NULL,
  "PRICE" int NOT NULL
);
 
CREATE TABLE "ORDER_ITEMS" (
  "ORDER_ID" int,
  "PRODUCT_NAME" varchar NOT NULL,
  "PRODUCT_UNIT" varchar NOT NULL,
  "PRODUCT_UNIT_PRICE" int NOT NULL,
  "QUANTITY" int NOT NULL,
  "TOTAL" int NOT NULL,
  "SORT_NUMBER" int NOT NULL
);
 
ALTER TABLE "ORDER_ITEMS" ADD FOREIGN KEY ("ORDER_ID") REFERENCES "ORDERS" ("ID");
